name: fcdl
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pytorch-cuda=11.7
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pip
  - pip:
    - numpy>=1.20.0,<1.24
    - numba>=0.52.0,<=0.53.1
    - scipy>=1.2.3
    - matplotlib
    - seaborn
    - scikit-image
    - gym
    - tensorboard
    - h5py
    - scikit-learn
    - pybullet-svl>=3.1.6.4
    - hidapi
    - pygame
    - open3d
    - wandb
    - pytest